# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9f60ffac2f1b7de2250c06601ecdba1302f50fdf90425f3f3be22dde08480d7d4d0d7aea570f9a9c4b6561ce822d95971c143d76f8938d02b437b74fd451284

test:
  secret_key_base: bb618b3e2a18b892fc94596281f636847b5dbdbdfbaeba68ea8010efba762fd78d331a2c261bd19b3decc400d62a0e9e1b18dd5d733181e01c9520dd47b5156e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c9f60ffac2f1b7de2250c06601ecdba6302f50fdf90425f3f3be22dde08480d7d4d0d7aea570f9a9c4b6561ce822d95971c143d76f8938d02b437b74fd451284
